/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewPromotion.java
 *
 * Created on 18 déc. 2011, 00:56:51
 */

package emalaedesktopapplication.forms;

import database.entity.Formation;
import database.entity.Promotion;
import database.entity.UserProfile;
import javax.swing.DefaultListModel;

/**
 *
 * @author pc
 */
public class ViewPromotion extends javax.swing.JPanel {

    private DefaultListModel selectedFormationListModel;

    /** Creates new form ViewPromotion */
    public ViewPromotion() {
        initComponents();
    }

    public void setPromotion(Promotion promotion)
    {
        String promoName = promotion.getName();
        UserProfile responsible = promotion.getResponsible();
        Integer promoYear = promotion.getPromotionYear();
        promotionNameValue.setText(promoName);
        if (responsible != null)
        {
            responsibleNameValue.setText(responsible.getFullName());
        }
        if (promoYear != null)
        {
            yearValue.setText(promoYear.toString());
        }

        selectedFormationListModel = new DefaultListModel();
        for (Formation formation : promotion.getFormations())
        {
        selectedFormationListModel.addElement(formation.getName());
        }
        formationList.setModel(selectedFormationListModel);

        selectedFormationListModel = new DefaultListModel();
        for (UserProfile user : promotion.getApprentices())
        {
        selectedFormationListModel.addElement(user.getFullName());
        }
        apprenticesList.setModel(selectedFormationListModel);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        promotionNameLabel = new javax.swing.JLabel();
        responsibleNameLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        apprenticesList = new javax.swing.JList();
        apprenticesLabel = new javax.swing.JLabel();
        formationsLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        formationList = new javax.swing.JList();
        promotionNameValue = new javax.swing.JLabel();
        responsibleNameValue = new javax.swing.JLabel();
        yearValue = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(emalaedesktopapplication.EmaLaeDesktopApplication.class).getContext().getResourceMap(ViewPromotion.class);
        setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("Form.border.title"))); // NOI18N
        setName("Form"); // NOI18N

        promotionNameLabel.setText(resourceMap.getString("promotionNameLabel.text")); // NOI18N
        promotionNameLabel.setName("promotionNameLabel"); // NOI18N

        responsibleNameLabel.setText(resourceMap.getString("responsibleNameLabel.text")); // NOI18N
        responsibleNameLabel.setName("responsibleNameLabel"); // NOI18N

        yearLabel.setText(resourceMap.getString("yearLabel.text")); // NOI18N
        yearLabel.setName("yearLabel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        apprenticesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        apprenticesList.setName("apprenticesList"); // NOI18N
        jScrollPane1.setViewportView(apprenticesList);

        apprenticesLabel.setText(resourceMap.getString("apprenticesLabel.text")); // NOI18N
        apprenticesLabel.setName("apprenticesLabel"); // NOI18N

        formationsLabel.setText(resourceMap.getString("formationsLabel.text")); // NOI18N
        formationsLabel.setName("formationsLabel"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        formationList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        formationList.setName("formationList"); // NOI18N
        jScrollPane2.setViewportView(formationList);

        promotionNameValue.setText(resourceMap.getString("promotionNameValue.text")); // NOI18N
        promotionNameValue.setName("promotionNameValue"); // NOI18N

        responsibleNameValue.setText(resourceMap.getString("responsibleNameValue.text")); // NOI18N
        responsibleNameValue.setName("responsibleNameValue"); // NOI18N

        yearValue.setText(resourceMap.getString("yearValue.text")); // NOI18N
        yearValue.setName("yearValue"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(promotionNameLabel)
                            .addComponent(responsibleNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yearLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yearValue)
                            .addComponent(responsibleNameValue)
                            .addComponent(promotionNameValue)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apprenticesLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formationsLabel))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(promotionNameLabel)
                    .addComponent(promotionNameValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(responsibleNameLabel)
                    .addComponent(responsibleNameValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(yearValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apprenticesLabel)
                    .addComponent(formationsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apprenticesLabel;
    private javax.swing.JList apprenticesList;
    private javax.swing.JList formationList;
    private javax.swing.JLabel formationsLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel promotionNameLabel;
    private javax.swing.JLabel promotionNameValue;
    private javax.swing.JLabel responsibleNameLabel;
    private javax.swing.JLabel responsibleNameValue;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JLabel yearValue;
    // End of variables declaration//GEN-END:variables

}
