/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewSession.java
 *
 * Created on 18 déc. 2011, 17:48:57
 */

package emalaedesktopapplication.forms;

import database.entity.CourseSession;

/**
 *
 * @author pc
 */
public class ViewSession extends javax.swing.JPanel {

    /** Creates new form ViewSession */
    public ViewSession() {
        initComponents();
    }


    public void setSession(CourseSession session)
    {
        // Default values
        String assignments = "none";

        if(session.getType() != null)
            typeValue.setText(session.getType().toString());
        if(session.getFormation() != null)
            formationValue.setText(session.getFormation().getName());
        if(session.getStartDate() != null)
            startDateValue.setText(session.getStartDate().toString());
        if (session.getEndDate() != null)
            endDateValue.setText(session.getEndDate().toString());
        if (session.getAssignmentsLink() != null)
            assignments = session.getAssignmentsLink();
        if (session.getTeacher() != null)
            teacherValue.setText(session.getTeacher().getFullName());

        assignmentsValue.setText(assignments);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeLabel = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        formationLabel = new javax.swing.JLabel();
        assignmentsLabel = new javax.swing.JLabel();
        typeValue = new javax.swing.JLabel();
        endDateValue = new javax.swing.JLabel();
        startDateValue = new javax.swing.JLabel();
        assignmentsValue = new javax.swing.JLabel();
        formationValue = new javax.swing.JLabel();
        teacherLabel = new javax.swing.JLabel();
        teacherValue = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(emalaedesktopapplication.EmaLaeDesktopApplication.class).getContext().getResourceMap(ViewSession.class);
        setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("Form.border.title"))); // NOI18N
        setName("Form"); // NOI18N

        typeLabel.setText(resourceMap.getString("typeLabel.text")); // NOI18N
        typeLabel.setName("typeLabel"); // NOI18N

        startDateLabel.setText(resourceMap.getString("startDateLabel.text")); // NOI18N
        startDateLabel.setName("startDateLabel"); // NOI18N

        endDateLabel.setText(resourceMap.getString("endDateLabel.text")); // NOI18N
        endDateLabel.setName("endDateLabel"); // NOI18N

        formationLabel.setText(resourceMap.getString("formationLabel.text")); // NOI18N
        formationLabel.setName("formationLabel"); // NOI18N

        assignmentsLabel.setText(resourceMap.getString("assignmentsLabel.text")); // NOI18N
        assignmentsLabel.setName("assignmentsLabel"); // NOI18N

        typeValue.setText(resourceMap.getString("typeValue.text")); // NOI18N
        typeValue.setName("typeValue"); // NOI18N

        endDateValue.setText(resourceMap.getString("endDateValue.text")); // NOI18N
        endDateValue.setName("endDateValue"); // NOI18N

        startDateValue.setText(resourceMap.getString("startDateValue.text")); // NOI18N
        startDateValue.setName("startDateValue"); // NOI18N

        assignmentsValue.setText(resourceMap.getString("assignmentsValue.text")); // NOI18N
        assignmentsValue.setName("assignmentsValue"); // NOI18N

        formationValue.setText(resourceMap.getString("formationValue.text")); // NOI18N
        formationValue.setName("formationValue"); // NOI18N

        teacherLabel.setText(resourceMap.getString("teacherLabel.text")); // NOI18N
        teacherLabel.setName("teacherLabel"); // NOI18N

        teacherValue.setText(resourceMap.getString("teacherValue.text")); // NOI18N
        teacherValue.setName("teacherValue"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(teacherLabel)
                                .addGap(6, 6, 6)
                                .addComponent(teacherValue)
                                .addGap(18, 18, 18)
                                .addComponent(typeLabel)
                                .addGap(30, 30, 30)
                                .addComponent(typeValue))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(startDateLabel)
                                .addGap(20, 20, 20)
                                .addComponent(startDateValue)
                                .addGap(18, 18, 18)
                                .addComponent(endDateLabel)
                                .addGap(28, 28, 28)
                                .addComponent(endDateValue))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(formationLabel)
                        .addGap(37, 37, 37)
                        .addComponent(formationValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(assignmentsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(assignmentsValue)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherLabel)
                    .addComponent(teacherValue)
                    .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formationLabel)
                    .addComponent(formationValue)
                    .addComponent(assignmentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignmentsValue))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endDateLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(endDateValue))
                    .addComponent(startDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateValue))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assignmentsLabel;
    private javax.swing.JLabel assignmentsValue;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JLabel endDateValue;
    private javax.swing.JLabel formationLabel;
    private javax.swing.JLabel formationValue;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JLabel startDateValue;
    private javax.swing.JLabel teacherLabel;
    private javax.swing.JLabel teacherValue;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel typeValue;
    // End of variables declaration//GEN-END:variables
}
