/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewFormation.java
 *
 * Created on 17 déc. 2011, 20:07:49
 */

package emalaedesktopapplication.forms;

import database.entity.CourseSession;
import database.entity.Formation;
//import database.entity.Session;
import javax.swing.DefaultListModel;

/**
 *
 * @author pc
 */
public class ViewFormation extends javax.swing.JPanel {

    private DefaultListModel selectedFormationListModel;
    /** Creates new form ViewFormation */
    public ViewFormation()
    {
        initComponents();
    }


    public void setFormation(Formation formation)
    {
        formationNameValue.setText(formation.getName());
        if (formation.getParentFormation() != null)
        {
            parentFormationNameValue.setText(formation.getParentFormation().getName());
            // TODO: what is this (below) for Simon?
            // parentFormationParentValue.setText(formation.getParentFormation().getParentFormation().getName());
        }
        
        ViewSession viewSession;
        for (CourseSession session: formation.getSessions())
        {
            viewSession = new ViewSession();
            viewSession.setSession(session);
            formationDetailsTabbedPane.addTab(
                    session.toString(), viewSession);

        }
        
        /*
        selectedFormationListModel = new DefaultListModel();
        for (Formation childFormation : formation.getChildrenFormations())
        {
            selectedFormationListModel.addElement(childFormation.getName());
        }
        childrenFormationsList.setModel(selectedFormationListModel);
         */

        /*
         * FIXME : Sessions need to be implemented in business class
        selectedFormationListModel = new DefaultListModel();
        for (Session session : formation.getSessions())
        {
            selectedFormationListModel.addElement(session.getName());
        }
        sessionsList.setModel(selectedFormationListModel);
         *
         */
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentFormationPanel = new javax.swing.JPanel();
        parentFormationParentLabel = new javax.swing.JLabel();
        parentFormationNameLabel = new javax.swing.JLabel();
        parentFormationNameValue = new javax.swing.JLabel();
        parentFormationParentValue = new javax.swing.JLabel();
        formationNameLabel = new javax.swing.JLabel();
        formationNameValue = new javax.swing.JLabel();
        formationDetailsTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        childrenFormationsList = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(emalaedesktopapplication.EmaLaeDesktopApplication.class).getContext().getResourceMap(ViewFormation.class);
        setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("Form.border.title"))); // NOI18N
        setAutoscrolls(true);
        setName("Form"); // NOI18N

        parentFormationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("parentFormationPanel.border.title"))); // NOI18N
        parentFormationPanel.setName("parentFormationPanel"); // NOI18N

        parentFormationParentLabel.setText(resourceMap.getString("parentFormationParentLabel.text")); // NOI18N
        parentFormationParentLabel.setName("parentFormationParentLabel"); // NOI18N

        parentFormationNameLabel.setText(resourceMap.getString("parentFormationNameLabel.text")); // NOI18N
        parentFormationNameLabel.setName("parentFormationNameLabel"); // NOI18N

        parentFormationNameValue.setText(resourceMap.getString("parentFormationNameValue.text")); // NOI18N
        parentFormationNameValue.setName("parentFormationNameValue"); // NOI18N

        parentFormationParentValue.setText(resourceMap.getString("parentFormationParentValue.text")); // NOI18N
        parentFormationParentValue.setName("parentFormationParentValue"); // NOI18N

        javax.swing.GroupLayout parentFormationPanelLayout = new javax.swing.GroupLayout(parentFormationPanel);
        parentFormationPanel.setLayout(parentFormationPanelLayout);
        parentFormationPanelLayout.setHorizontalGroup(
            parentFormationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parentFormationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parentFormationNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parentFormationNameValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(parentFormationParentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parentFormationParentValue)
                .addGap(55, 55, 55))
        );
        parentFormationPanelLayout.setVerticalGroup(
            parentFormationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parentFormationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parentFormationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parentFormationParentLabel)
                    .addComponent(parentFormationNameLabel)
                    .addComponent(parentFormationNameValue)
                    .addComponent(parentFormationParentValue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formationNameLabel.setText(resourceMap.getString("formationNameLabel.text")); // NOI18N
        formationNameLabel.setName("formationNameLabel"); // NOI18N

        formationNameValue.setText(resourceMap.getString("formationNameValue.text")); // NOI18N
        formationNameValue.setName("formationNameValue"); // NOI18N

        formationDetailsTabbedPane.setName("formationDetailsTabbedPane"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        childrenFormationsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        childrenFormationsList.setName("childrenFormationsList"); // NOI18N
        jScrollPane1.setViewportView(childrenFormationsList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(262, 262, 262))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );

        formationDetailsTabbedPane.addTab(resourceMap.getString("jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        formationDetailsTabbedPane.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formationDetailsTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addComponent(parentFormationPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formationNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(formationNameValue)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formationNameLabel)
                    .addComponent(formationNameValue))
                .addGap(18, 18, 18)
                .addComponent(parentFormationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formationDetailsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        parentFormationPanel.getAccessibleContext().setAccessibleName(resourceMap.getString("parentFormationPanel.AccessibleContext.accessibleName")); // NOI18N
        formationDetailsTabbedPane.getAccessibleContext().setAccessibleName(resourceMap.getString("jTabbedPane1.AccessibleContext.accessibleName")); // NOI18N

        getAccessibleContext().setAccessibleName(resourceMap.getString("Form.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList childrenFormationsList;
    private javax.swing.JTabbedPane formationDetailsTabbedPane;
    private javax.swing.JLabel formationNameLabel;
    private javax.swing.JLabel formationNameValue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel parentFormationNameLabel;
    private javax.swing.JLabel parentFormationNameValue;
    private javax.swing.JPanel parentFormationPanel;
    private javax.swing.JLabel parentFormationParentLabel;
    private javax.swing.JLabel parentFormationParentValue;
    // End of variables declaration//GEN-END:variables
}
