/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminEditUserPanel.java
 *
 * Created on Nov 20, 2011, 2:36:54 PM
 */

package emalaedesktopapplication.forms.admin;

import database.entity.User;
import javax.swing.JComponent;
import org.metawidget.inspector.annotation.MetawidgetAnnotationInspector;
import org.metawidget.inspector.composite.CompositeInspector;
import org.metawidget.inspector.composite.CompositeInspectorConfig;
import org.metawidget.inspector.hibernate.validator.HibernateValidatorInspector;
import org.metawidget.inspector.iface.Inspector;
import org.metawidget.inspector.java5.Java5Inspector;
import org.metawidget.inspector.jpa.JpaInspector;
import org.metawidget.inspector.propertytype.PropertyTypeInspector;
import org.metawidget.swing.SwingMetawidget;

/**
 *
 * @author andre
 */
public class AdminEditUserPanel extends javax.swing.JPanel {

    private User user;
    private SwingMetawidget metawidget;
    // private PersonTest user;

    /** Creates new form AdminEditUserPanel */
    public AdminEditUserPanel() {
        initComponents();
    }

    // public AdminEditUserPanel(User user) {
    public AdminEditUserPanel(User user) {
        this();
        this.user = user;
        initMetaWidget();
        populateMetaWidgetValuesFromObject();
    }

    /*
     * FIXME: I though metawidget could do that automagically
     */
    private void populateMetaWidgetValuesFromObject()
    {
        metawidget.setValue( user.getUsername(), new String[] {"username"} );
        // user.setFirstname( (String) metawidget.getValue( "firstname" ) );
    }

    /**
     * FIXME: I though metawidget could do that automagically
     * Saves all current widget values back to the object and returns it
     * @return updated object
     */
    public User save()
    {
        user.setUsername( (String) metawidget.getValue( new String[] {"username"} ) );

        return user;
    }

    private void initMetaWidget()
    {
        metawidget = new SwingMetawidget();
        CompositeInspectorConfig inspectorConfig =
                new CompositeInspectorConfig();
        Inspector[] inspectors = { new PropertyTypeInspector(),
                    new MetawidgetAnnotationInspector(),
                    new Java5Inspector(),
                    new JpaInspector(),
                    /* new HibernateValidatorInspector() */};
        inspectorConfig.setInspectors(inspectors);
        metawidget.setInspector( new CompositeInspector( inspectorConfig ) );

        metawidget.setToInspect( user );
        setMiddleContentPanel(metawidget);
    }

    /**
     * Replace the old middleContentPanel with the given one
     * @param panel to set in the middle
     */
    // public void setMiddleContentPanel(JPanel panel)
    public void setMiddleContentPanel(JComponent panel)
    {
        middleContentPanel.removeAll();
        panel.setVisible(true);
        middleContentPanel.add(panel,
                "FIXME: constraint must be a string, see #14");
        middleContentPanel.revalidate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        middleContentPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(emalaedesktopapplication.EmaLaeDesktopApplication.class).getContext().getResourceMap(AdminEditUserPanel.class);
        middleContentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("middleContentPanel.border.title"))); // NOI18N
        middleContentPanel.setName("middleContentPanel"); // NOI18N
        middleContentPanel.setLayout(new java.awt.CardLayout());

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(middleContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(middleContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel middleContentPanel;
    // End of variables declaration//GEN-END:variables

}
