/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManyToManySelectorPanel.java
 *
 * Created on Dec 8, 2011, 8:53:03 AM
 */

package emalaedesktopapplication.forms.admin;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author andre
 */
public class ManyToManySelectorPanel extends javax.swing.JPanel {

    DefaultListModel allObjectsListModel;
    DefaultListModel selectedObjectsListModel;

    /** Creates new form ManyToManySelectorPanel */
    public ManyToManySelectorPanel() {
        initComponents();
        customInitComponents();
    }

    public void setAllObjectsListFromObjects(Object[] objects)
    {
        for (int i = 0; i < objects.length; i++)
        {
            if(!selectedObjectsListModel.contains(objects[i]))
            {
                allObjectsListModel.add(i, objects[i]);
            }
        }
    }

    public void setSelectedObjectsListFromObjects(Object[] objects)
    {
        for (int i = 0; i < objects.length; i++)
        {
            if(!allObjectsListModel.contains(objects[i]))
            {
                selectedObjectsListModel.add(i, objects[i]);
            }
        }
    }



    /**
     * Changes the JList model
     */
    private void customInitComponents()
    {
        String[] items = new String[] {}; // {"foo", "bar", "foobar"};
        allObjectsListModel = new DefaultListModel();
        selectedObjectsListModel = new DefaultListModel();
        for (int i = 0; i < items.length; i++)
        {
            allObjectsListModel.add(i, items[i]);
            selectedObjectsListModel.add(i, items[i]);
        }

        allObjectsList.setModel(allObjectsListModel);
        selectedObjectsList.setModel(selectedObjectsListModel);
    }

    /**
     * Moves an item from the all list box to the selected list box
     * @param index
     */
    private void moveToSelected(int index)
    {
        // getSelectedSelectedObjectList
        Object obj = allObjectsListModel.remove(index);
        selectedObjectsListModel.addElement(obj);
    }

    /**
     * Removes an item from the selected list box back to the all list box
     * @param index
     */
    private void removeFromSelected(int index)
    {
        Object obj = selectedObjectsListModel.remove(index);
        allObjectsListModel.addElement(obj);
    }

    /**
     * TODO: use JList.getSelectedValues instead
     * @param list
     * @return
     */
    private Object[] getSelectedObjectList(javax.swing.JList list)
    {
        Object sel;
        List objects = new ArrayList();
        // Get the index of all the selected items
        int[] selectedIx = list.getSelectedIndices();

        // Get all the selected items using the indices
        for (int i=0; i<selectedIx.length; i++) {
            sel = list.getModel().getElementAt(selectedIx[i]);
            objects.add(sel);
        }

        return objects.toArray();
    }

    /**
     * @return the selected objects of the allObjectsList
     */
    private Object[] getSelectedAllObjectList()
    {
        return getSelectedObjectList(allObjectsList);
    }

    /**
     * @return the selected objects of the selectedObjectsList
     */
    private Object[] getSelectedSelectedObjectList()
    {
        return getSelectedObjectList(selectedObjectsList);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        allObjectsList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectedObjectsList = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        allObjectsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        allObjectsList.setName("allObjectsList"); // NOI18N
        jScrollPane1.setViewportView(allObjectsList);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        selectedObjectsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        selectedObjectsList.setName("selectedObjectsList"); // NOI18N
        jScrollPane2.setViewportView(selectedObjectsList);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(emalaedesktopapplication.EmaLaeDesktopApplication.class).getContext().getResourceMap(ManyToManySelectorPanel.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        moveToSelected(allObjectsList.getSelectedIndex());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        removeFromSelected(selectedObjectsList.getSelectedIndex());
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList allObjectsList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList selectedObjectsList;
    // End of variables declaration//GEN-END:variables

}
